### ISSUE TITLE
Moving text via drag and drop inserts clipboard instead

### ISSUE THREAD

**Issue by rillig** [holgerbrandl/pasteimages#22] opened 2019-11-21 02:12 UTC
(See [IDEA-227306](https://youtrack.jetbrains.com/issue/IDEA-227306) for the full story.)

~~~text
// Target:

// From the clipboard

// Text to be moved
~~~

What steps will reproduce the issue?
1. Start a JetBrains IDE with the Paste Images plugin 1.2.4 enabled.
2. Have the above text in an editor
3. Select "From the clipboard", press Ctrl+C
4. Select "Text to be moved"
5. Using the mouse, move the selected text after "Target:"

What is the expected result?

~~~text
// Target:Text to be moved
~~~

What happens instead?

~~~text
// Target:From the clipboard
~~~

The text "Text to be moved" has disappeared.

**Comment by holgerbrandl** [comment] 2019-11-22 10:47
Duplicate of #11

**Closed by holgerbrandl** 2019-11-22 10:47 UTC
